server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://localhost:8081
          predicates:
            - Path=/orders/**, 
        - id: cooking
          uri: http://localhost:8082
          predicates:
            - Path=/cookings/**, 
        - id: delevery
          uri: http://localhost:8083
          predicates:
            - Path=/deeliveries/**, 
        - id: notification
          uri: http://localhost:8084
          predicates:
            - Path=, 
        - id: dashboard
          uri: http://localhost:8085
          predicates:
            - Path=, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://order:8080
          predicates:
            - Path=/orders/**, 
        - id: cooking
          uri: http://cooking:8080
          predicates:
            - Path=/cookings/**, 
        - id: delevery
          uri: http://delevery:8080
          predicates:
            - Path=/deeliveries/**, 
        - id: notification
          uri: http://notification:8080
          predicates:
            - Path=, 
        - id: dashboard
          uri: http://dashboard:8080
          predicates:
            - Path=, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
